//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSView.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DriverDetail
    {
        public int Id { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        public System.DateTime Dob { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string ProfilePhotoUrl { get; set; }
        [Required]
        public string DriverLicenceFrontUrl { get; set; }
    }
}
